# 数据库连接配置
jdbc.url=jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
jdbc.username=root
jdbc.password=940429
jdbc.driver=com.mysql.cj.jjdbcc.Driver

# 连接池配置（HikariCP）
pool.poolName=rbac-pool
pool.maximumPoolSize=10
pool.minimumIdle=5
pool.connectionTimeout=30000
pool.idleTimeout=600000
pool.maxLifetime=1800000